---
# statsd service:
- name: restart statsd
  systemd:
    name: statsd
    enabled: True
    state: restarted
    daemon_reload: True

# Producer service:
- name: restart producer
  systemd:
    name: producer
    enabled: True
    state: restarted
    daemon_reload: True
